package model.finance;

import DB.DBConnection;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

import java.io.*;
import java.sql.*;
import java.time.LocalDate;

public class ReportGenerator {

    private static final String REPORTS_DIR = "reports";

    static {
        new File(REPORTS_DIR).mkdirs();
    }

    // 1. Sales + Purchases + Profit Report (Text File)
    public static void generateSalesReport(String dateStr) {
        LocalDate date = LocalDate.parse(dateStr);
        String fileName = REPORTS_DIR + "/sales_report_" + dateStr + ".pdf";

        try (Connection conn = DBConnection.getConnection();
             BufferedWriter bw = new BufferedWriter(new FileWriter(fileName))) {

            bw.write("=".repeat(80) + "\n");
            bw.write("       DAILY SALES & PURCHASES REPORT - " + dateStr + "\n");
            bw.write("=".repeat(80) + "\n\n");

            double totalSales = writeSalesSection(bw, conn, date);
            double totalPurchases = writePurchasesSection(bw, conn, date);
            double profit = totalSales - totalPurchases;

            writeProfitSection(bw, totalSales, totalPurchases, profit);

            bw.write("\n" + "=".repeat(80) + "\n");
            bw.write("                   Generated by Ziad\n");
            bw.write("=".repeat(80) + "\n");

            System.out.println("Sales report generated: " + fileName);

        } catch (Exception e) {
            System.err.println("Error in sales report: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // 2. Real Bar Chart (PNG Image)
    public static void generateProfitGraph(String dateStr) {
        LocalDate date = LocalDate.parse(dateStr);
        String fileName = REPORTS_DIR + "/profit_graph_" + dateStr + ".png";

        try (Connection conn = DBConnection.getConnection()) {

            double sales = getTotalSales(conn, date);
            double purchases = getTotalPurchases(conn, date);
            double profit = sales - purchases;

            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            dataset.addValue(sales, "Amount", "Sales");
            dataset.addValue(purchases, "Amount", "Purchases");
            dataset.addValue(profit, "Amount", "Profit");

            JFreeChart barChart = ChartFactory.createBarChart(
                    "Profit & Loss - " + dateStr,
                    "Category",
                    "Amount (EGP)",
                    dataset
            );

            int width = 800, height = 600;
            ChartUtilities.saveChartAsPNG(new File(fileName), barChart, width, height);

            System.out.println("Real graph generated: " + fileName + " (PNG Image)");

        } catch (Exception e) {
            System.err.println("Error generating graph: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // --- Helper Methods ---

    private static double writeSalesSection(BufferedWriter bw, Connection conn, LocalDate date) throws SQLException, IOException {
        String sql = """
            SELECT i.ID, i.date, si.Discount, per.name AS customer, p.Name AS product, p.Price, e.User_name
            FROM invoice i
            JOIN sell_invoice si ON i.ID = si.Invoice_ID
            JOIN customer c ON si.Customer_Person_ID = c.Person_ID
            JOIN person per ON c.Person_ID = per.ID
            JOIN employee_has_invoice ehi ON i.ID = ehi.Invoice_ID
            JOIN employee e ON ehi.Employee_User_name = e.User_name
            JOIN invoice_has_product ihp ON i.ID = ihp.Invoice_ID
            JOIN product p ON ihp.Product_parcode = p.parcode
            WHERE DATE(i.date) = ?
            ORDER BY i.ID
            """;

        double total = 0;
        bw.write("1. SALES\n");
        bw.write("-".repeat(70) + "\n");
        bw.write(String.format("%-8s %-12s %-8s %-15s %-25s %-8s %-12s%n",
                "Invoice", "Date", "Disc.", "Customer", "Product", "Price", "Employee"));
        bw.write("-".repeat(70) + "\n");

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, date.toString());
            ResultSet rs = ps.executeQuery();

            int lastInv = -1;
            double invTotal = 0;

            while (rs.next()) {
                int id = rs.getInt("ID");
                if (id != lastInv && lastInv != -1) {
                    bw.write(String.format("%50s %-8.2f%n", "Invoice Total:", invTotal));
                    total += invTotal;
                    invTotal = 0;
                }
                if (id != lastInv) {
                    bw.write(String.format("%-8d %-12s %-8.2f %-15s%n",
                            id, rs.getDate("date"), rs.getDouble("Discount"), rs.getString("customer")));
                    lastInv = id;
                }
                bw.write(String.format("%50s %-25s %-8.2f %-12s%n",
                        "", rs.getString("product"), rs.getDouble("Price"), rs.getString("User_name")));
                invTotal += rs.getDouble("Price");
            }
            if (lastInv != -1) {
                bw.write(String.format("%50s %-8.2f%n", "Invoice Total:", invTotal));
                total += invTotal;
            }
        }
        bw.write("-".repeat(70) + "\n");
        bw.write(String.format("%50s %-8.2f%n\n", "Total Sales:", total));
        return total;
    }

    private static double writePurchasesSection(BufferedWriter bw, Connection conn, LocalDate date) throws SQLException, IOException {
        String sql = """
            SELECT i.ID, i.date, i.price, pi.money_paid, pi.remaing_money, s.nane AS supplier
            FROM invoice i
            JOIN purchase_invoce pi ON i.ID = pi.Invoice_ID
            JOIN supplier s ON pi.Supplier_nane = s.nane
            WHERE DATE(i.date) = ?
            """;

        double total = 0;
        bw.write("2. PURCHASES\n");
        bw.write("-".repeat(70) + "\n");
        bw.write(String.format("%-8s %-12s %-10s %-10s %-10s %-18s%n",
                "Invoice", "Date", "Total", "Paid", "Remain", "Supplier"));
        bw.write("-".repeat(70) + "\n");

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, date.toString());
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                double price = rs.getDouble("price");
                bw.write(String.format("%-8d %-12s %-10.2f %-10.2f %-10.2f %-18s%n",
                        rs.getInt("ID"), rs.getDate("date"), price,
                        rs.getDouble("money_paid"), rs.getDouble("remaing_money"), rs.getString("supplier")));
                total += price;
            }
        }
        bw.write("-".repeat(70) + "\n");
        bw.write(String.format("%50s %-10.2f%n\n", "Total Purchases:", total));
        return total;
    }

    private static void writeProfitSection(BufferedWriter bw, double sales, double purchases, double profit) throws IOException {
        bw.write("3. PROFIT & LOSS SUMMARY\n");
        bw.write("-".repeat(50) + "\n");
        bw.write(String.format("%-20s %10.2f%n", "Total Sales:", sales));
        bw.write(String.format("%-20s %10.2f%n", "Total Purchases:", purchases));
        bw.write(String.format("%-20s %10.2f%n", "Net Profit:", profit));
        bw.write("-".repeat(50) + "\n\n");
    }

    private static double getTotalSales(Connection conn, LocalDate date) throws SQLException {
        String sql = """
            SELECT COALESCE(SUM(p.Price), 0)
            FROM invoice i
            JOIN sell_invoice si ON i.ID = si.Invoice_ID
            JOIN invoice_has_product ihp ON i.ID = ihp.Invoice_ID
            JOIN product p ON ihp.Product_parcode = p.parcode
            WHERE DATE(i.date) = ?
            """;
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, date.toString());
            ResultSet rs = ps.executeQuery();
            return rs.next() ? rs.getDouble(1) : 0;
        }
    }

    private static double getTotalPurchases(Connection conn, LocalDate date) throws SQLException {
        String sql = """
            SELECT COALESCE(SUM(i.price), 0)
            FROM invoice i
            JOIN purchase_invoce pi ON i.ID = pi.Invoice_ID
            WHERE DATE(i.date) = ?
            """;
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, date.toString());
            ResultSet rs = ps.executeQuery();
            return rs.next() ? rs.getDouble(1) : 0;
        }
    }
}