package model.finance;

import DB.DBConnection;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

import java.io.*;
import java.sql.*;
import java.time.LocalDate;

public class ReportGenerator {
    private static final String REPORTS_DIR = "reports";

    static {
        new File(REPORTS_DIR).mkdirs();
    }

    public static void generateSalesReport(String dateStr) {
        LocalDate date = LocalDate.parse(dateStr);
        String fileName = REPORTS_DIR + "/sales_report_" + dateStr + ".txt";

        try (Connection conn = DBConnection.getConnection();
             BufferedWriter bw = new BufferedWriter(new FileWriter(fileName))) {

            bw.write("=".repeat(80) + "\n");
            bw.write(" DAILY SALES & PURCHASES REPORT - " + dateStr + "\n");
            bw.write("=".repeat(80) + "\n\n");

            double totalSales = writeSalesSection(bw, conn, date);
            double totalPurchases = writePurchasesSection(bw, conn, date);
            double profit = totalSales - totalPurchases;

            writeProfitSection(bw, totalSales, totalPurchases, profit);

            bw.write("\n" + "=".repeat(80) + "\n");
            bw.write(" Generated by Ziad\n");
            bw.write("=".repeat(80) + "\n");

            System.out.println("Sales report generated: " + fileName);

        } catch (Exception e) {
            System.err.println("Error in sales report: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public static void generateProfitGraph(String dateStr) {
        LocalDate date = LocalDate.parse(dateStr);
        String fileName = REPORTS_DIR + "/profit_graph_" + dateStr + ".png";

        try (Connection conn = DBConnection.getConnection()) {
            double sales = getTotalSales(conn, date);
            double purchases = getTotalPurchases(conn, date);
            double profit = sales - purchases;

            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            dataset.addValue(sales, "Amount", "Sales");
            dataset.addValue(purchases, "Amount", "Purchases");
            dataset.addValue(profit, "Amount", "Profit");

            JFreeChart barChart = ChartFactory.createBarChart(
                    "Profit & Loss - " + dateStr,
                    "Category",
                    "Amount (EGP)",
                    dataset
            );

            int width = 800, height = 600;
            ChartUtilities.saveChartAsPNG(new File(fileName), barChart, width, height);
            System.out.println("Real graph generated: " + fileName);

        } catch (Exception e) {
            System.err.println("Error generating graph: " + e.getMessage());
            e.printStackTrace();
        }
    }


    private static double writeSalesSection(BufferedWriter bw, Connection conn, LocalDate date) throws SQLException, IOException {
        String sql = """
            SELECT 
                i.ID, 
                i.date, 
                COALESCE(si.Discount, 0) AS Discount,
                per.name AS customer_name,
                p.Name AS product_name,
                (ihp.units * (p.Price / CASE WHEN p.Uints > 0 THEN p.Uints ELSE 1 END)) AS line_total,
                emp.User_name
            FROM invoice i
            JOIN sell_invoice si ON i.ID = si.Invoice_ID
            LEFT JOIN customer c ON si.Customer_Person_ID = c.Person_ID
            LEFT JOIN person per ON c.Person_ID = per.ID
            LEFT JOIN employee emp ON i.employee_User_name = emp.User_name 
                             AND i.employee_Person_ID = emp.Person_ID 
                             AND i.employee_bransh_ID = emp.bransh_ID
            JOIN invoice_has_product ihp ON i.ID = ihp.Invoice_ID
            JOIN product p ON ihp.Product_parcode = p.parcode
            WHERE i.date >= ? AND i.date <= ?
            ORDER BY i.ID, ihp.Product_parcode
            """;

        double grandTotal = 0;
        bw.write("1. SALES\n");
        bw.write("-".repeat(80) + "\n");
        bw.write(String.format("%-10s %-12s %-8s %-20s %-25s %-10s %-12s%n",
                "Invoice", "Date", "Disc.", "Customer", "Product", "Line Total", "Employee"));
        bw.write("-".repeat(80) + "\n");

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, date.toString() + " 00:00:00");
            ps.setString(2, date.toString() + " 23:59:59");
            ResultSet rs = ps.executeQuery();

            int currentInvoice = -1;
            double invoiceTotal = 0;

            while (rs.next()) {
                int invId = rs.getInt("ID");

                if (invId != currentInvoice && currentInvoice != -1) {
                    bw.write(String.format("%-68s Invoice Total: %10.2f%n", "", invoiceTotal));
                    grandTotal += invoiceTotal;
                    invoiceTotal = 0;
                }

                if (invId != currentInvoice) {
                    bw.write(String.format("%-10d %-12s %-8.2f %-20s%n",
                            invId,
                            rs.getDate("date"),
                            rs.getDouble("Discount"),
                            rs.getString("customer_name") != null ? rs.getString("customer_name") : "Walk-in"));
                    currentInvoice = invId;
                }

                bw.write(String.format("%58s %-25s %10.2f   %-12s%n",
                        "",
                        rs.getString("product_name"),
                        rs.getDouble("line_total"),
                        rs.getString("User_name") != null ? rs.getString("User_name") : "N/A"));

                invoiceTotal += rs.getDouble("line_total");
            }

            if (currentInvoice != -1) {
                bw.write(String.format("%-68s Invoice Total: %10.2f%n", "", invoiceTotal));
                grandTotal += invoiceTotal;
            }
        }

        bw.write("-".repeat(80) + "\n");
        bw.write(String.format("%-68s GRAND TOTAL SALES: %10.2f%n\n", "", grandTotal));
        return grandTotal;
    }

    private static double writePurchasesSection(BufferedWriter bw, Connection conn, LocalDate date) throws SQLException, IOException {
        String sql = """
            SELECT 
                i.ID, 
                i.date, 
                i.price AS total_price,
                pi.money_paid,
                COALESCE(pi.remaing_money, 0) AS remaing_money,
                s.nane AS supplier_name
            FROM invoice i
            JOIN purchase_invoce pi ON i.ID = pi.Invoice_ID
            JOIN supplier s ON pi.Supplier_nane = s.nane AND pi.Supplier_phone = s.phone
            WHERE i.date >= ? AND i.date <= ?
            ORDER BY i.ID
            """;

        double totalPurchases = 0;

        bw.write("\n2. PURCHASES\n");
        bw.write("-".repeat(80) + "\n");
        bw.write(String.format("%-10s %-12s %-12s %-12s %-12s %-20s%n",
                "Invoice", "Date", "Total", "Paid", "Remaining", "Supplier"));
        bw.write("-".repeat(80) + "\n");

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, date.toString() + " 00:00:00");
            ps.setString(2, date.toString() + " 23:59:59");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                double total = rs.getDouble("total_price");
                bw.write(String.format("%-10d %-12s %-12.2f %-12.2f %-12.2f %-20s%n",
                        rs.getInt("ID"),
                        rs.getDate("date"),
                        total,
                        rs.getDouble("money_paid"),
                        rs.getDouble("remaing_money"),
                        rs.getString("supplier_name")));

                totalPurchases += total;
            }
        }

        bw.write("-".repeat(80) + "\n");
        bw.write(String.format("%-68s TOTAL PURCHASES: %10.2f%n\n", "", totalPurchases));
        return totalPurchases;
    }

    private static void writeProfitSection(BufferedWriter bw, double sales, double purchases, double profit) throws IOException {
        bw.write("\n3. PROFIT & LOSS SUMMARY\n");
        bw.write("-".repeat(50) + "\n");
        bw.write(String.format("%-25s %15.2f EGP%n", "Total Sales:", sales));
        bw.write(String.format("%-25s %15.2f EGP%n", "Total Purchases:", purchases));
        bw.write("-".repeat(50) + "\n");
        bw.write(String.format("%-25s %15.2f EGP%n", "NET PROFIT:", profit));
        bw.write("-".repeat(50) + "\n");
    }

    private static double getTotalSales(Connection conn, LocalDate date) throws SQLException {
        // Updated to use the total price stored in the invoice header (more accurate & faster)
        String sql = """
            SELECT COALESCE(SUM(i.price), 0)
            FROM invoice i
            JOIN sell_invoice si ON i.ID = si.Invoice_ID
            WHERE i.date >= ? AND i.date <= ?
            """;

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, date.toString() + " 00:00:00");
            ps.setString(2, date.toString() + " 23:59:59");
            ResultSet rs = ps.executeQuery();
            return rs.next() ? rs.getDouble(1) : 0;
        }
    }

    private static double getTotalPurchases(Connection conn, LocalDate date) throws SQLException {
        String sql = """
            SELECT COALESCE(SUM(i.price), 0)
            FROM invoice i
            JOIN purchase_invoce pi ON i.ID = pi.Invoice_ID
            WHERE i.date >= ? AND i.date <= ?
            """;

        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, date.toString() + " 00:00:00");
            ps.setString(2, date.toString() + " 23:59:59");
            ResultSet rs = ps.executeQuery();
            return rs.next() ? rs.getDouble(1) : 0;
        }
    }
}