package enums;

public enum Category {

    MEDICINE,
    COSMETIC,
    BABY_CARE,
    VITAMINS,
    FIRST_AID,
    SKINCARE,
    ORAL_CARE,
    HAIR_CARE,
    HYGIENE,
    WOMEN_CARE,
    MEN_CARE,
    NUTRITION,
    DEVICES,

    // Medicine categories
    PAINKILLER,             
    ANTIBIOTIC,             
    ANTIVIRAL,              
    ANTI_INFLAMMATORY,      
    ANTI_ALLERGIC,          
    ANTI_DIABETIC,          
    CARDIO,                 
    GI,                     
    ANTI_ACID,              
    COLD_AND_FLU,           
    RESPIRATORY,            
    HORMONAL,               
    DERMATOLOGY,            
    NEUROLOGY,              
    PSYCHIATRY,             
    MUSCLE_RELAXANT,        
    EYE_CARE_MED,           
    EAR_CARE_MED,           
    KIDNEY,                 
    LIVER,                  
    BLOOD,                  
    IMMUNE_SYSTEM,          
    GYNECOLOGY,             
    PEDIATRIC,              
    TOPICAL,                

    // Other categories
    SUPPLEMENTS,            
    PROTEIN,                
    BEAUTY,                 
    MAKEUP,                 
    BODY_CARE,              
    SUNSCREEN,              
    FRAGRANCE,              
    SHAVING,                
    DIET_PRODUCTS,          
    COVID_SUPPLIES,         
    TEST_DEVICES,           
    BANDAGES,               
    DISINFECTANTS           
}
